services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GitZenith\:
    resource: '../src/*'

  GitZenith\App\Controller\:
    resource: '../src/App/Controller'
    tags: ['controller.service_arguments']

  GitZenith\App\Controller\Commit:
    arguments:
      $perPage: '%commits_per_page%'
    tags: ['controller.service_arguments']

  GitZenith\App\Controller\Blob:
    arguments:
      $perPage: '%commits_per_page%'
    tags: ['controller.service_arguments']

  GitZenith\Repository\Index:
    arguments:
      $paths: '%repositories%'
      $excludePaths: '%exclude_repositories%'
      $depth: '%repository_depth%'
      $systems:
        - '@GitZenith\SCM\System\Git\CommandLine'
        - '@GitZenith\SCM\System\Mercurial\CommandLine'

  GitZenith\SCM\System\Git\CommandLine:
    arguments:
      $path: '%git_path%'

  GitZenith\SCM\System\Mercurial\CommandLine:
    arguments:
      $path: '%hg_path%'

  GitZenith\App\Twig\AvatarExtension:
    arguments:
      $avatarUrl: '%avatar_url%'
      $avatarConfig: '%avatar_config%'
