name: Release Build

on:
  release:
    types: [released]

jobs:

  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
    env:
      REPONAME: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: npm install

      - name: Build package
        run: make build

      - name: Rename package to current tag
        run: mv build.zip $REPONAME-${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: $REPONAME-${{ github.ref_name }}.zip
