name: Release Build

on:
  release:
    types: [released]

jobs:

  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set GITHUB_ENV variables
        run: |
          echo "REPONAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: npm install

      - name: Build package
        run: make build

      - name: Rename package
        run: |
          mv build.zip ${{ env.REPONAME }}-${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: ${{ env.REPONAME }}-${{ github.ref_name }}.zip
